In [21]:
import numpy as np

In [22]:
signal=np.genfromtxt('/home/avnsh9/workspace/checkmate2/results/My_New_Run/analysis/myprocess_cms1703_test_signal.dat', skip_header=14,skip_footer=7,usecols=4)

In [23]:
signal

array([ 3256.34,  3256.34, 22794.4 ,  1628.17,  2261.34,  1266.35,
        1628.17,  3256.34,  4613.14,  3799.06,  4613.14,  4522.69,
        5608.13,  5065.41,  5336.77,  6422.22,  4974.96,  5336.77,
        4703.6 ,  4432.23,  3346.79,  4160.87])

In [6]:
signal

array([ 4794.05,  5879.5 , 32925.2 ,  1628.17,  1989.98,  2080.44,
        2532.71,  3437.24,  5517.68,  4160.87,  5155.86,  4974.96,
        6874.49,  6603.13,  8412.2 ,  8412.2 ,  6241.31,  6331.76,
        7236.3 ,  7236.3 ,  5427.23,  6603.13])

In [24]:
s=np.append(signal,[signal[0],signal[1],signal[2]])

In [25]:
s_new=np.delete(s,[0,1,2])

In [26]:
s_new

array([ 1628.17,  2261.34,  1266.35,  1628.17,  3256.34,  4613.14,
        3799.06,  4613.14,  4522.69,  5608.13,  5065.41,  5336.77,
        6422.22,  4974.96,  5336.77,  4703.6 ,  4432.23,  3346.79,
        4160.87,  3256.34,  3256.34, 22794.4 ])

In [27]:
bin=np.loadtxt('data1703.dat',skiprows=1,usecols=3)

In [28]:
bin

array([30., 30., 30., 30., 30., 40., 40., 40., 40., 40., 40., 50., 50.,
       50., 50., 50., 60., 60., 60., 70., 70., 80.])

In [29]:
result=np.divide(s_new,bin)

In [30]:
result

array([ 54.27233333,  75.378     ,  42.21166667,  54.27233333,
       108.54466667, 115.3285    ,  94.9765    , 115.3285    ,
       113.06725   , 140.20325   , 126.63525   , 106.7354    ,
       128.4444    ,  99.4992    , 106.7354    ,  94.072     ,
        73.8705    ,  55.77983333,  69.34783333,  46.51914286,
        46.51914286, 284.93      ])